Projects popup window
virag-ky/Microverse-Portfolio pull request #10
Opened 2022-03-02 20:23 UTC by virag-ky

We created a pop-up window for the projects section (desktop-mobile version).
By clicking the 'See Project' button, the pop-up window appears and the body background becomes black and blurred.
We created 2 functions, the 'createInfo' function, which is getting the elements from the project and storing them in the 'projects array'. 
The second function, the 'createDiv' function, creates the pop-up window and appends the elements from the 'projects array'.
Also, in the 'createDiv' function, we created 3 buttons (Live Site, Source, and the exit button) and a paragraph.

2022-03-02 20:37 UTC, ReshyResh requested changes
# Hi team, 

### Good job so far!
  - ✔ Popup works as expected.
  - ✔ No linter errors.
  - ✔ Design matches Figma template on all screen sizes.


#### You did a good job implementing the popup but it seems like you forgot a part of the requirement, please check the comments below.


## Required Changes ♻️
_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! 👏👏👏

----

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-02 20:37 UTC, ReshyResh commented on script.js
> +  description.classList.add('popup-paragraph');
- [ ] Following the above mentioned change, this description will need to match the description from the project object. Currently, it is the same for every popup. Remember, the popup details must be filled getting the data from the project object, for example 
````
const projects = [{
    name: "Project one",
    description: "Description for project one.",
    image: "link_to_image.jpg",
    technologies: ["HTML", "JavaScript", "CSS"],
    link: "link_to_live_version.com",
}]
```
`

2022-03-02 20:38 UTC, ReshyResh commented on script.js
> +
- [ ] The projects array is currently empty. Please make sure that, as per requirement, 
  - For each project you need to store the following pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, link to source.
  - You need to update the main page so that the projects section is created dynamically using the information stored in that JavaScript object. Remember, all of the HTML in that section is created when the page loads. 

This means that you need to change your code in `index.html` , removing all the hard-coded projects and replacing them with an empty section that will be filled dynamically using javascript, taking the informations (Title, description etc..) from the project objects. This will make adding projects in the future easy and your code way cleaner 👍

2022-03-03 13:45 UTC, virag-ky commented
We removed all the hard-coded projects from the index.html file and created the function that creates the projects when the page loads.
The project data is stored in the 'projects' array, as objects.

2022-03-03 14:05 UTC, keroloussamy approved these changes
Hi @virag-ky, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️
- Add all the requirements. ✔️

![clap](https://media0.giphy.com/media/j2GPljpvL8Lulm3d0X/giphy.gif)

## Optional suggestions
_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-03 14:10 UTC, merged